language: objective-c
osx_image: xcode8.2
env:
  global:
  - PROJECT=KWDataSourceKit.xcodeproj
  - IOS_FRAMEWORK_SCHEME="KWDataSourceKit iOS"
  - TVOS_FRAMEWORK_SCHEME="KWDataSourceKit tvOS"
  - IOS_SDK=iphonesimulator10.2
  - TVOS_SDK=appletvsimulator10.1
  - IOS_EXAMPLE_SCHEME="iOS Example"
  matrix:
    - DESTINATION="OS=8.4,name=iPhone 5"                                                  SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"   BUILD_EXAMPLE="YES"   EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"
    - DESTINATION="OS=9.3,name=iPhone 6"                                                  SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"   BUILD_EXAMPLE="YES"   EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"
    - DESTINATION="id:E40727B3-41FB-4D6E-B4CB-BFA87109EB12,OS=10.2,name=iPhone 7"         SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"   BUILD_EXAMPLE="YES"   EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"
    - DESTINATION="OS=9.2,name=Apple TV 1080p"                                            SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="YES"   BUILD_EXAMPLE="NO"    EXAMPLE_SCHEME="$TVOS_EXAMPLE_SCHEME"
    - DESTINATION="OS=10.1,name=Apple TV 1080p"                                           SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="YES"   BUILD_EXAMPLE="NO"    EXAMPLE_SCHEME="$TVOS_EXAMPLE_SCHEME"

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
    else
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

after_script:
  - sleep 5
